include(test_macros)
MACRO(RUN_CASE case)
  FILE(READ sif/${case}.params CASE_PARAMS)
  FILE(WRITE sif/case.params "${CASE_PARAMS}")
  RUN_ELMER_TEST()
ENDMACRO()

IF(MPIEXEC_NTASKS GREATER 1)
  FILE(REMOVE_RECURSE rings/partitioning.${MPIEXEC_NTASKS})
  execute_process(COMMAND ${ELMERGRID_BIN} 2 2 rings -metiskway ${MPIEXEC_NTASKS} -nooverwrite)
ENDIF()
FOREACH(case order_ab order_ba)
  RUN_CASE(${case})
ENDFOREACH()

# Slabs of equal element count along y (ElmerGrid -partition): a partition owns the outer winding but not the inner
# one, and when the outer winding is the first component its W is solved there with no electrode face of its own.
IF(MPIEXEC_NTASKS GREATER 1)
  FILE(REMOVE_RECURSE rings/partitioning.${MPIEXEC_NTASKS})
  EXECUTE_PROCESS(COMMAND ${ELMERGRID_BIN} 2 2 rings -partition 1 ${MPIEXEC_NTASKS} 1)
  # The trigger: a partition that owns the outer winding (body 2) and none of the inner one (body 1).
  SET(OUTER_ONLY_PARTS 0)
  FOREACH(part RANGE 1 ${MPIEXEC_NTASKS})
    FILE(STRINGS rings/partitioning.${MPIEXEC_NTASKS}/part.${part}.elements INNER_ELEMENTS REGEX "^ *[0-9]+ +1 ")
    FILE(STRINGS rings/partitioning.${MPIEXEC_NTASKS}/part.${part}.elements OUTER_ELEMENTS REGEX "^ *[0-9]+ +2 ")
    IF(OUTER_ELEMENTS AND NOT INNER_ELEMENTS)
      MATH(EXPR OUTER_ONLY_PARTS "${OUTER_ONLY_PARTS} + 1")
    ENDIF()
  ENDFOREACH()
  IF(OUTER_ONLY_PARTS EQUAL 0)
    MESSAGE(FATAL_ERROR "No partition owns the outer winding without the inner one")
  ENDIF()
  FOREACH(case order_ab order_ba)
    RUN_CASE(${case})
  ENDFOREACH()
ENDIF()
