include(test_macros)
RUN_ELMER_TEST()

# The SIF name holds "--", which XML forbids inside a comment: every header comment of the .vtu must stay valid.
FILE(GLOB_RECURSE VTU_FILES "${CMAKE_CURRENT_BINARY_DIR}/*.vtu")
IF(NOT VTU_FILES)
  MESSAGE(FATAL_ERROR "No .vtu file written")
ENDIF()
FOREACH(vtu IN LISTS VTU_FILES)
  FILE(READ "${vtu}" VTU_HEAD LIMIT 4096)
  STRING(REGEX MATCHALL "<!--[^>]*-->" COMMENTS "${VTU_HEAD}")
  IF(NOT COMMENTS)
    MESSAGE(FATAL_ERROR "${vtu}: no header comment")
  ENDIF()
  FOREACH(comment IN LISTS COMMENTS)
    STRING(LENGTH "${comment}" COMMENT_LENGTH)
    MATH(EXPR INNER_LENGTH "${COMMENT_LENGTH} - 7")
    STRING(SUBSTRING "${comment}" 4 ${INNER_LENGTH} INNER)
    STRING(FIND "${INNER}" "--" POS)
    IF(NOT POS EQUAL -1)
      MESSAGE(FATAL_ERROR "${vtu}: \"--\" inside an XML comment: ${comment}")
    ENDIF()
  ENDFOREACH()
  STRING(FIND "${VTU_HEAD}" "<!-- Solver input file: case- -hyphen.sif -->" POS)
  IF(POS EQUAL -1)
    MESSAGE(FATAL_ERROR "${vtu}: no XML-safe solver input file comment")
  ENDIF()
ENDFOREACH()
