include(test_macros)
IF(MPIEXEC_NTASKS GREATER 1)
  FILE(REMOVE_RECURSE rings/partitioning.${MPIEXEC_NTASKS})
ENDIF()
execute_process(COMMAND ${ELMERGRID_BIN} 2 2 rings -metiskway ${MPIEXEC_NTASKS} -nooverwrite)
# One run per case. RUN_ELMER_TEST checks the pinned norm; each "! expect:" line
# of the case must also appear in the solver output: the final layout of each
# component, which must not change with the partitioning or the component order.
MACRO(RUN_CASE case)
  FILE(READ sif/${case}.params CASE_PARAMS)
  FILE(WRITE sif/case.params "${CASE_PARAMS}")
  RUN_ELMER_TEST()
  STRING(REGEX MATCHALL "! expect: [^\r\n]*" EXPECTS "${CASE_PARAMS}")
  FOREACH(expect IN LISTS EXPECTS)
    STRING(REPLACE "! expect: " "" expect "${expect}")
    STRING(FIND "${TEST_STDOUT_VARIABLE}" "${expect}" POS)
    IF(POS EQUAL -1)
      MESSAGE(FATAL_ERROR "Case ${case}: \"${expect}\" not in the solver output")
    ENDIF()
  ENDFOREACH()
ENDMACRO()

FOREACH(case fit overflow order_ab order_ba passive mixed_floor mixed_share)
  RUN_CASE(${case})
ENDFOREACH()

# Slabs of equal element count along y (ElmerGrid -partition): the last slab owns no element of either winding,
# the one before it none of the inner winding, and those partitions still take part in the plan's collectives.
# (order_ba with these slabs crashes in the W potential solver of touching windings, with or without this change.)
IF(MPIEXEC_NTASKS GREATER 1)
  FILE(REMOVE_RECURSE rings/partitioning.${MPIEXEC_NTASKS})
  EXECUTE_PROCESS(COMMAND ${ELMERGRID_BIN} 2 2 rings -partition 1 ${MPIEXEC_NTASKS} 1)
  FOREACH(body 1 2)
    SET(EMPTY_PARTS 0)
    FOREACH(part RANGE 1 ${MPIEXEC_NTASKS})
      FILE(STRINGS rings/partitioning.${MPIEXEC_NTASKS}/part.${part}.elements BODY_ELEMENTS REGEX "^ *[0-9]+ +${body} ")
      IF(NOT BODY_ELEMENTS)
        MATH(EXPR EMPTY_PARTS "${EMPTY_PARTS} + 1")
      ENDIF()
    ENDFOREACH()
    IF(EMPTY_PARTS EQUAL 0)
      MESSAGE(FATAL_ERROR "Every partition owns elements of body ${body}")
    ENDIF()
  ENDFOREACH()
  RUN_CASE(order_ab)
ENDIF()
