include(test_macros)
# DEV-1157: LoadFields sums the result files of a harmonic run; 64 or more files stopped it on the message line.
# Two result files are written with the solver (h1: every field 1, h2: every field 2), the other 68 are copies of them
# (odd k: h1, even k: h2), so 70 files h1..h70.result are read and LoadWm3 must sum to 35 x 1 + 35 x 2 = 105.
# Few solver launches on purpose: 70 EXECUTE_PROCESS calls in one cmake script stopped launching after about 50 on Windows.
execute_process(COMMAND ${ELMERGRID_BIN} 1 2 cube)
SET(N 70)
SET(LIST "")
SET(SUM 0)
FILE(READ sif/write.sif.in WRITE_TEMPLATE)
FOREACH(k 1 2)
  STRING(REPLACE "@K@" "${k}" WRITE_SIF "${WRITE_TEMPLATE}")
  FILE(WRITE sif/write.sif "${WRITE_SIF}")
  EXECUTE_ELMER_SOLVER(sif/write.sif)
ENDFOREACH()
FOREACH(k RANGE 1 ${N})
  MATH(EXPR odd "${k} % 2")
  IF(odd)
    SET(weight 1)
  ELSE()
    SET(weight 2)
  ENDIF()
  IF(k GREATER 2)
    FILE(COPY_FILE cube/h${weight}.result cube/h${k}.result)
  ENDIF()
  SET(LIST "${LIST} ${k}")
  MATH(EXPR SUM "${SUM} + ${weight}")
ENDFOREACH()
FILE(READ sif/load.sif.in LOAD_TEMPLATE)
STRING(REPLACE "@N@" "${N}" LOAD_SIF "${LOAD_TEMPLATE}")
STRING(REPLACE "@LIST@" "${LIST}" LOAD_SIF "${LOAD_SIF}")
STRING(REPLACE "@SUM@" "${SUM}" LOAD_SIF "${LOAD_SIF}")
FILE(WRITE sif/load.sif "${LOAD_SIF}")
FILE(WRITE ELMERSOLVER_STARTINFO "sif/load.sif\n")
RUN_ELMER_TEST()
