include(test_macros)
# DEV-1157: Foster reluctivity ladders of order 2 and 4 on a stranded coil. Every case is written from
# sif/2241.sif.in with its ladder and values and must pass on its own; N4 (each pole split in two) must give the
# value of N2, and the startup case must end without proximity loss.
SET(FAILED_CASES "")
FILE(READ sif/2241.sif.in TEMPLATE)
FOREACH(case N2 N4 N2bdf2 edge startup)
  FILE(READ sif/${case}.ladder LADDER)
  STRING(REPLACE "@LADDER@" "${LADDER}" SIF "${TEMPLATE}")
  FILE(WRITE sif/2241.sif "${SIF}")
  FILE(READ sif/${case}.params PARAMS)
  FILE(WRITE sif/case.params "${PARAMS}")
  FILE(REMOVE 2241/dat/proximity.dat)
  RUN_ELMER_TEST()
  # first column of proximity.dat: the integral of the proximity loss, W (half model)
  FILE(STRINGS 2241/dat/proximity.dat ROWS)
  SET(PEAK 0)
  SET(LAST 0)
  FOREACH(row ${ROWS})
    SEPARATE_ARGUMENTS(COLUMNS UNIX_COMMAND "${row}")
    LIST(GET COLUMNS 0 value)
    SET(LAST ${value})
    IF(value GREATER PEAK)
      SET(PEAK ${value})
    ENDIF()
  ENDFOREACH()
  MESSAGE(STATUS "${case}: proximity loss last ${LAST} W, largest ${PEAK} W")
  IF(case STREQUAL "startup")
    IF(NOT LAST LESS 1.0E-9 OR LAST LESS -1.0E-12 OR NOT PEAK GREATER 1.0E-6)
      LIST(APPEND FAILED_CASES "${case}: last ${LAST} largest ${PEAK}")
    ENDIF()
  ENDIF()
ENDFOREACH()
# mixed: order 2 and order 4 in one model, on two disjoint copies of the mesh
execute_process(COMMAND ${ELMERGRID_BIN} 2 2 2241 -clone 2 1 1 -clonesize 500 0 0 -cloneinds -out 2241x2)
FILE(READ sif/mixed.sif.in TEMPLATE)
FILE(READ sif/N2.ladder LADDER)
FILE(READ sif/N4.ladder LADDER2)
STRING(REPLACE "@LADDER@" "${LADDER}" SIF "${TEMPLATE}")
STRING(REPLACE "@LADDER2@" "${LADDER2}" SIF "${SIF}")
FILE(WRITE sif/2241.sif "${SIF}")
FILE(READ sif/mixed.params PARAMS)
FILE(WRITE sif/case.params "${PARAMS}")
FILE(REMOVE 2241/dat/proximity.dat)
RUN_ELMER_TEST()
FILE(STRINGS 2241/dat/proximity.dat ROWS)
LIST(GET ROWS -1 LAST)
SEPARATE_ARGUMENTS(COLUMNS UNIX_COMMAND "${LAST}")
LIST(GET COLUMNS 0 LAST)
MESSAGE(STATUS "mixed: proximity loss last ${LAST} W")
IF(FAILED_CASES)
  MESSAGE(FATAL_ERROR "Test failed: ${FAILED_CASES}")
ENDIF()
